name: Build and Deploy [DEV]

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [ 12.x ]
    steps:

      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Configure committer
        run: |
          git config user.name "curtisblanchette"
          git config user.email "<curtis@4iiz.com>"

      # Bumps the Version number based on patterns found in the commit message
      - name: Generate CHANGELOG + Bump Version
        run: |
          npm i -g standard-version
          npm run release
          git push --follow-tags origin develop
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build Application
        run: npm run build:dev
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 sync ./dist/ s3://dominion-ui-dev --delete

      - name: Create CloudFront Cache Invalidation
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DEV_ID }}
          PATHS: "/*"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
